apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: test-key
  AWS_SECRET_ACCESS_KEY: test-secret-key
  AWS_ENDPOINTS: http://10.0.2.2:9001
  AWS_CERT: ""
  VIRTUAL_HOSTED_STYLE: "false"
